### ISSUE TITLE
Date problem

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#100]
The date format we choose in settings is used only in few strings.
But MANY other dates are still with the OLD format. Such as file details, app settings, history, login log, etc...
Please use the format we choose for ALL date in the app!

Some dates are still:

```
mm-dd
YYYY-mm-dd
dd-mm
```

And also some use the format i choose _**(dd/mm/YYY)**_ but they are without year and is wrong!
`dd/mm` <-- wrong

The correct way is ONE of this two:
`dd/mm/YYYY`
or
`dd/MMM` (with the NAME of the month)

_**P.S. Time should be customizable too, because in the US they use 12h but in Europe we use 24h.**_

**Comment by kalcaddle** [comment]
fixed on 1.30.03.

**Comment by RallyTuning** [comment]
Yes, now is correct. But the months name are in english.

(Still don't understand why you use day and month only if the year is same as we are now. Would be very nice if you add the ability to write manually the date format. For example a custom box where we can write "dd", "MM", "YYYY", etc...)

By the way, thanks
